### ISSUE TITLE
Feature Request: Texture replacements

### ISSUE THREAD

**Issue by Firdoser** [libretro/swanstation#41] opened 2022-10-10 22:44 UTC
**Texture packs feature!**
Actually in retroarch only Beetle PSX HW have this feature, but
It would be awesome if this feature were implemented in Duck.. i mean Swanstation the near future!
Cheers!!

**Comment by DarthMew** [comment] 2023-02-02 14:27
Duplicate of https://github.com/libretro/swanstation/issues/33

**Closed as not planned by DarthMew** 2023-02-02 14:27 UTC
